# wt zsh integration — generated by `wt shell-init zsh`.
# Wire it up with one line in ~/.zshrc:
#
#   eval "$(wt shell-init zsh)"

# The cd protocol (PLAN.md D11): cd-producing commands print their
# target path on stdout, and this wrapper performs the cd the
# binary cannot. Every other command passes through untouched, so
# scripts that call `wt` under the wrapper see identical behavior.
# A pre-existing `wt` alias would expand inside this very eval and
# abort it wholesale; clear it, and use the `function` keyword,
# whose name position is never alias-expanded.
builtin unalias wt 2>/dev/null
function wt {
  # emulate pins zsh semantics against exotic user setopts;
  # builtins dodge same-named user functions and aliases.
  emulate -L zsh
  case "${1-}" in
  ""|go|new)
    local out
    out="$(command wt "$@")" || return $?
    if [[ -n "$out" && -d "$out" ]]; then
      builtin cd -- "$out" || return $?
      # $(wt ...) runs this wrapper in a subshell where the cd is
      # invisible; hand the path through so capture keeps working.
      [[ -t 1 ]] || builtin print -r -- "$out"
    elif [[ -n "$out" ]]; then
      builtin print -r -- "$out"
    fi
    ;;
  *)
    command wt "$@"
    ;;
  esac
}

# Completions come from the binary itself, so they can never go
# stale; compdef only exists once compinit has run, and without it
# there is nothing to register with. Registration is lazy — the
# real script loads on the first completion — so shells that never
# tab-complete wt pay no extra binary spawn at startup.
if (( ${+functions[compdef]} )); then
  _wt_bootstrap() {
    # By the time a completion runs, compsys has already
    # sanitized exotic setopts (ksh_arrays and friends), so a
    # plain eval is safe here — and deliberately unwrapped:
    # sticky emulation would leak into compsys internals and
    # leave _describe unable to offer matches. The script's
    # final compdef rebinds wt straight to _wt for later Tabs.
    eval "$(command wt completion zsh)"
    builtin unfunction _wt_bootstrap
    _wt "$@"
  }
  compdef _wt_bootstrap wt
fi

# Prompt indicator (opt-in): WT_PROMPT carries the tree's name
# while the cwd is inside a linked worktree, for use like
#   PROMPT='...${WT_PROMPT:+ ⌂$WT_PROMPT}...'   (with setopt prompt_subst)
# Pure zsh — a few stats and one builtin read, recomputed only on
# cd, never per prompt render (PLAN.md R14). Deliberately uncached:
# trees come and go, and a cache would pin a dead answer for the
# life of the shell.
_wt_prompt_update() {
  emulate -L zsh
  unset WT_PROMPT
  local dir="$PWD" line
  while [[ -n "$dir" && "$dir" != / ]]; do
    if [[ -f "$dir/.git" ]]; then
      # a .git *file* marks a linked worktree: its gitdir line
      # points into the repository's shared .git/worktrees/<name>
      IFS= read -r line < "$dir/.git" 2>/dev/null
      if [[ "$line" == gitdir:*/worktrees/* ]]; then
        export WT_PROMPT="${dir:t}"
      fi
      break
    elif [[ -e "$dir/.git" ]]; then
      break
    fi
    dir="${dir:h}"
  done
  return 0
}
builtin emulate zsh -c 'autoload -Uz add-zsh-hook'
add-zsh-hook chpwd _wt_prompt_update
_wt_prompt_update
