# wt zsh integration — generated by `wt shell-init zsh`.
# Wire it up with one line in ~/.zshrc:
#
#   eval "$(wt shell-init zsh)"

# The cd protocol (PLAN.md D11): cd-producing commands print their
# target path on stdout, and this wrapper performs the cd the
# binary cannot. Every other command passes through untouched, so
# scripts that call `wt` under the wrapper see identical behavior.
wt() {
  # emulate pins zsh semantics against exotic user setopts;
  # builtins dodge same-named user functions and aliases.
  emulate -L zsh
  case "${1-}" in
  ""|go|new)
    local out
    out="$(command wt "$@")" || return $?
    if [[ -n "$out" && -d "$out" ]]; then
      builtin cd -- "$out"
    elif [[ -n "$out" ]]; then
      builtin print -r -- "$out"
    fi
    ;;
  *)
    command wt "$@"
    ;;
  esac
}

# Completions come from the binary itself, so they can never go
# stale; compdef only exists once compinit has run, and without it
# there is nothing to register with.
if (( $+functions[compdef] )); then
  eval "$(command wt completion zsh)"
fi
